[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tuna_contract = "4FKoWL8LcBxy2RNvUierSC6gX7bsJvTwzvvxVbosmpce"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.mainnet.solana.com"
wallet = '/home/tuna.pet/tuna-wallets/dev-keypair.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
