[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tuna_contract = "4FKoWL8LcBxy2RNvUierSC6gX7bsJvTwzvvxVbosmpce"

[programs.testnet]
tuna_contract = "BWh9JaJ7PkPCdTuVE2Fe7niB655k7koU9vC8URt35MR9"
[programs]
tuna_contract = "BWh9JaJ7PkPCdTuVE2Fe7niB655k7koU9vC8URt35MR9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = '/home/tuna.pet/tuna-wallets/dev-keypair.json'

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
